update confirm on leave
scoutmaker/scoutmaker-web-v2 pull request #113
Opened 2022-12-31 00:05 UTC by dejwi

### Task Description
[SCOUT-280](https://playmakerpro.atlassian.net/browse/SCOUT-280?atlOrigin=eyJpIjoiMThlYzBiN2ZjODk4NGZhZDlhOWM0OTA2MzI2ZjcyOTQiLCJwIjoiaiJ9)

- now prompt is activated after you've clicked any form field

2023-01-03 17:10 UTC, jakubfiglak requested changes
How about refactoring `ConfirmOnLeaveForm` component to a hook?

2023-01-03 17:10 UTC, jakubfiglak commented on src/utils/hooks/use-confirm-leave.ts
> +}
What's the point of making a component that returns null off of it? It could just be another hook that doesn't return anything

2023-01-03 22:41 UTC, dejwi commented on src/utils/hooks/use-confirm-leave.ts
> +}
It's like that because of one issue - `useFormikContext` only works when called in a component thats INSIDE component with `<Formik>` element

Theoretically a hook could exist in which you pass a formik ref but that's getting more complicated
I think it's a really elegant solution where you just insert one component without any props and it all just works

It returns null so it could be even used as a component

2023-01-04 07:52 UTC, jakubfiglak approved these changes

2023-01-04 22:36 UTC, merged