Feat/scout 24 comp age categories
scoutmaker/scoutmaker-web-v2 pull request #20
Opened 2022-08-09 14:34 UTC by dejwi

[SCOUT-24](https://playmakerpro.atlassian.net/browse/SCOUT-24?atlOrigin=eyJpIjoiZDBiM2IxNTI4YmE4NGI0MjhmNjdjYzZkZDllNzQzNGYiLCJwIjoiaiJ9)

### Task Description
Competition age categories
- table
- create/edit form
- translations
- index/create/edit/id pages
- admin role check
- add to admin panel

### Additional Notes (optional)
- no filter form as there's literally no filtering for competition age categories
- commits duplicated after my merge attempt:(

2022-08-09 18:57 UTC, jakubfiglak requested changes
There are some minor issues to be addressed (please see my comments), but other than that, as usual, fantastic work 🚀 

We're gonna need to adjust to some backend changes - as you can see there's no `list` endpoint for this module & regular `GET /` endpoint acts as a list (there's no pagination or sorting available). This is something I need to fix and make consistent throughout entire API and when it's done, we will adjust frontend code (I will create separate ticket for that)

2022-08-09 18:57 UTC, jakubfiglak commented on public/locales/pl/common.json
> +  "COMPETITION_AGE_CATEGORY": "Kategoria wiekowa rozgrywki",
It should be `Kategoria wiekowa rozgrywek` I suppose:)

2022-08-09 18:57 UTC, jakubfiglak commented on src/components/icons/index.ts
> +  Category,
I think we should reexport this as `CategoryIcon` for consistency

2022-08-09 18:57 UTC, jakubfiglak commented on src/modules/competition-age-categories/forms/utils.ts
> +export const initialValues: CreateTeamDto = {
I think it's a leftover from another file, we should adjust it to match `CreateCompetitionAgeCategoryDto` :)

2022-08-09 18:57 UTC, jakubfiglak commented on src/modules/competition-age-categories/forms/utils.ts
> +      name: yup.string().required(t('teams:NO_NAME_ERROR')),
```suggestion
      name: yup.string().required(t('comp-age-categ:NO_NAME_ERROR')),
```

There's wrong i18n namespace used here and translations don't work properly

![Screenshot 2022-08-09 at 20 40 30](https://user-images.githubusercontent.com/55458549/183738659-612f64a4-d74b-4b7a-bcd7-8f447c2fc171.png)

Please adjust:)

2022-08-09 21:13 UTC, dejwi commented on src/modules/competition-age-categories/forms/utils.ts
> +      name: yup.string().required(t('teams:NO_NAME_ERROR')),
added separatly with other changes and accepting suggestion and merge is blocked:c

2022-08-10 07:42 UTC, jakubfiglak approved these changes

2022-08-10 08:37 UTC, merged