Feat/scout 23 competitions module
scoutmaker/scoutmaker-web-v2 pull request #22
Opened 2022-08-11 20:03 UTC by dejwi

[SCOUT-23](https://playmakerpro.atlassian.net/browse/SCOUT-23?atlOrigin=eyJpIjoiNTY4ZDVjMWZkN2U1NGRkNmI4ZGFmODc0Y2YyZmU2ODQiLCJwIjoiaiJ9)

### Task Description
Competitions module
- table
- create/edit form
- translations
- index/create/edit/id pages
- add to panel
- edit/delete admin
- create/edit pages admin
- other components base

### Additional Notes (optional)
- can't get data from endpoint using other role than admin
- some unfinished endpoints as before, mostly marked with `// UPDATE IN FUTURE`
- I'm not sure about my translations🥲

2022-08-12 19:46 UTC, jakubfiglak requested changes
Actually, this module is meant to be admin-only and that's why there're errors for other user roles. Sorry if the ticket description confused you. Please move navigation item to `ADMIN PANEL` & protect all pages.

We have an issue with `level` input (please see in-code comments)

![Screenshot 2022-08-12 at 20 55 46](https://user-images.githubusercontent.com/55458549/184431723-18083c51-c4ef-4ab6-99af-f43bca8cab11.png)

And with `competitionJuniorLevel` validation (it should not be required)

![Screenshot 2022-08-12 at 20 57 57](https://user-images.githubusercontent.com/55458549/184432029-fcd5faed-4870-476d-8350-9641d663ddd7.png)

Other than that - great work, as always 🚀

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competition-age-categories/combot.tsx
> +import { AutocompleteRenderInputParams, TextField } from '@mui/material'
There's a typo in file name, please change to `combo` :)

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/details-card.tsx
> +type IDetailsCard = {
Please do not prefix type name with an `I`. This prefix is there to indicate this is an `interface`. I think I've used interfaces for components props everywhere, so I think we should keep consistency. Also, it should be suffixed with `Props` -> `IDetailsCardProps`

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/details-card.tsx
> +  comp: CompetitionDto
I'd rather not use such shortcuts, please use full `competition` here

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/forms/create.tsx
> +            <Field
We cannot let users pick negative values here or 0. Also, the value needs to be an integer. We need to think of a way to ensure that. I think the easiest solution would be to create a select field here (with values of `1, 2, 3, ..., 15`) but if you prefer handling this another way, please do.  

PS. We have the same issue in `FilterForm`

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/forms/filter.tsx
> +            <Field
Same issue as in `CreateForm`

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/forms/utils.ts
> +        required: true,
This field is not required, please remove this constraint

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/genders-combo.tsx
> +import { AutocompleteRenderInputParams, TextField } from '@mui/material'
I don't think we need a combo for this - there's only two possible values. Please refactor this to a regular select input (take `FootedSelect` component as an example)

2022-08-12 19:46 UTC, jakubfiglak commented on src/modules/competitions/table/row.tsx
> +      <StyledTableCell>{t(`${gender}S`)}</StyledTableCell>
Honestly, I'd just display `M` or `K` in Polish here and `M` or `F` in English

2022-08-15 12:21 UTC, jakubfiglak requested changes
Two little things left to change and we're good to go:)

2022-08-15 12:21 UTC, jakubfiglak commented on src/modules/competitions/forms/utils.ts
> +  level: 0,
I'd set the default level to 1 here (0 is not even a valid value)

2022-08-15 12:24 UTC, jakubfiglak commented
> note: edit&create both have 1-15 level validation, filter form is left without it as min/max props dont work and I think yup validation is bit too much in a filter form as it doesnt affect data, but can be added if needed

You're right - yup is an overkill in case of filter form. But, we can use native HTML validation and set `inputProps` on our field to set `min`, `max`, `step` & perhaps `pattern` value to ensure client is not sending invalid requests to the backend.

https://stackoverflow.com/questions/8808590/number-input-type-that-takes-only-integers
https://medium.com/codex/making-html-5-numeric-inputs-only-accept-integers-d3d117973d56

2022-08-16 10:35 UTC, dejwi commented
min/max/step/pattern only prevents invalid input when using arrows to increment value, not when typing in value so I've added little helper text as well is that okay?

![image](https://user-images.githubusercontent.com/80927085/184859097-8b4c96bb-760c-4d98-a9fd-1fadc4ca84b9.png)

2022-08-16 18:57 UTC, jakubfiglak commented
> min/max/step/pattern only prevents invalid input when using arrows to increment value, not when typing in value so I've added little helper text as well is that okay?
> 
> ![image](https://user-images.githubusercontent.com/80927085/184859097-8b4c96bb-760c-4d98-a9fd-1fadc4ca84b9.png)

That's not exactly true - native html validation will prevent user from submitting the form if any of the values doesn't pass the validation (see attached screenshot)

![Screenshot 2022-08-16 at 20 54 42](https://user-images.githubusercontent.com/55458549/184958480-e75b854a-807f-4b4e-9153-bd7a5a5f5f59.png)

However the helper text thing is actually a good idea but I'd prefer using actual `helperText` prop for this. Example:

![Screenshot 2022-08-16 at 20 56 29](https://user-images.githubusercontent.com/55458549/184959187-f427349d-d103-44c9-a6f2-94e778c8e44d.png)

I will approve this PR though, we don't have to fix that now I suppose

2022-08-16 18:58 UTC, jakubfiglak approved these changes

2022-08-16 19:03 UTC, merged