Feat/scout 11 orders module
scoutmaker/scoutmaker-web-v2 pull request #24
Opened 2022-08-17 10:23 UTC by dejwi

[SCOUT-11](https://playmakerpro.atlassian.net/browse/SCOUT-11?atlOrigin=eyJpIjoiOTJjNzQzN2ZlOTMzNDFhMWFkY2ViYmNkMWYwZTQ3NWUiLCJwIjoiaiJ9)

### Task Description

Migrate orders module
- pages
- modules
- both^ without edit
- OrderStatusChip component

### Additional Notes (optional)

2022-08-18 16:00 UTC, jakubfiglak requested changes
As usual, great work 🚀 

There're some adjustments to be made though, please take a look at my in-code comments

2022-08-18 16:41 UTC, dejwi commented on src/modules/orders/table/row.tsx
> +        <Badge badgeContent={_count.reports} color="secondary">
just a sidenote it worked with count higher than zero and I didnt notice || '0' passed as **string** in v1 🙆‍♂️🙆‍♂️🙆‍♂️🙆‍♂️

2022-08-18 17:39 UTC, jakubfiglak commented on src/modules/orders/table/row.tsx
> +        <Badge badgeContent={_count.reports} color="secondary">
Yeah, it looks like this component doesn't display a badge if `badgeContent === 0`. That makes sense if you use it for example to show some notifications count. In our case, we want to display 0, so the string was a hack to do so:)

You can always check the docs - https://mui.com/material-ui/react-badge/

2022-08-19 15:20 UTC, jakubfiglak reviewed
We're getting close, just two minor comments:)

2022-08-19 15:20 UTC, jakubfiglak commented on src/modules/orders/table/row.tsx
> +      <CellWithLink href={`/teams/${player?.teams[0].team.slug}`} label={player?.teams[0].team.name || ''} />
Please use `getSingleTeamRoute` function here

2022-08-19 15:20 UTC, jakubfiglak commented on src/modules/orders/table/row.tsx
> +      <CellWithLink href={`/matches/${match?.id}`} label={match ? `${match?.homeTeam.name} vs ${match.awayTeam.name}` : ''} />
Please use `getSingleMatchRoute` function here & `getMatchDisplayName` for the `label`.

I'd like to create these kind of functions for all of our modules to reduce the amount of repeated code (like building labels - we do this stuff all around the app) so please existing functions or write new ones if they've not been written before.

2022-08-22 18:16 UTC, jakubfiglak requested changes
Sorry, some more adjustments :D

2022-08-22 18:16 UTC, jakubfiglak commented on src/modules/orders/table/row.tsx
> +      <CellWithLink href={getSingleTeamRoute(player?.teams[0].team.slug || '')} label={player?.teams[0].team.name || ''} />
```suggestion
        {player?.teams[0] ? (
          <CellWithLink
            href={getSingleTeamRoute(player.teams[0].team.slug}
            label={player.teams[0].team.name}
          />
        ) : (
          <StyledTableCell>-</StyledTableCell>
        )}
```

Please do not render `CellWithLink` component when there's no team data

2022-08-22 18:16 UTC, jakubfiglak commented on src/modules/orders/table/row.tsx
> +      <CellWithLink href={getSingleMatchRoute(match?.id || 0)} label={match ? getMatchDisplayName({ awayTeamName: match.awayTeam.name, homeTeamName: match.homeTeam.name, competitionName: match.compet
```suggestion
        {match ? (
          <CellWithLink
            href={getSingleMatchRoute(match.id)}
            label={getMatchDisplayName({
              homeTeamName: match.homeTeam.name,
              awayTeamName: match.awayTeam.name,
            })}
          />
        ) : (
          <StyledTableCell>-</StyledTableCell>
        )}
```

Same here. And please omit `competitionName` in table cells, it's too much text

2022-08-22 18:16 UTC, jakubfiglak commented on src/utils/withSessionSsrRole.ts
> +        user,
I don't remember if I asked this before - why do we need user here?

2022-08-23 08:46 UTC, dejwi commented on src/utils/withSessionSsrRole.ts
> +        user,
It's used in index page at handleSetFilters in order to hack together showing only mine orders (userId query)

2022-08-23 08:55 UTC, jakubfiglak commented on src/utils/withSessionSsrRole.ts
> +        user,
I don't think there's a reason why we should do this server side. We have a `useUser` and we can get current user id using that on the client side. I'm gonna approve this PR anyway but let's keep in mind we should revisit this topic in the future.

2022-08-23 08:56 UTC, jakubfiglak approved these changes

2022-08-23 08:58 UTC, dejwi commented on src/utils/withSessionSsrRole.ts
> +        user,
ohh I didn't know about this hook 🙆‍♂️

2022-08-23 08:59 UTC, merged