Feat/scout 156 dashboard page
scoutmaker/scoutmaker-web-v2 pull request #46
Opened 2022-09-20 18:15 UTC by dejwi

### Task Description
**INTENTED TO USE WITH NEW BACKEND PR**

- dashboard page/modules
- create-translation script upgrade
- added react-countup package

### Additional Notes (optional)
I think you mentioned some hook to get id of a user but I couldn't find it

2022-09-25 13:08 UTC, jakubfiglak requested changes
Good work, there are some issues though. Please see my comments.

2022-09-25 13:08 UTC, jakubfiglak commented on src/pages/dashboard.tsx
> +    limit: 2,
Why are you fetching 2 reports?

2022-09-25 17:22 UTC, dejwi commented on src/pages/dashboard.tsx
> +    limit: 2,
forgot to mention that, backend doesnt allow to fetch only 1:p

2022-09-25 18:29 UTC, dejwi commented
yeah that shitty ass components was just my learning stage of mui:D All of them basically use same avatar component so I just extracted it. Btw I don't find using sx prop with more than short styling(especially when long theme props are used) appealing

2022-09-25 20:26 UTC, dejwi commented
I see that some types changed, especially from required to not required, for now I did enough to pass build but should I create ticket for overall changes ?

2022-09-26 14:16 UTC, jakubfiglak commented
> yeah these shitty ass components were just my learning stage of mui:D All of them basically use same avatar component so I just extracted it. Btw I don't find using sx prop with more than short styling(especially when long theme props are used) appealing

Yeah, it might seem a little hairy but it's a recommended way of adding custom styles to MUI components so we should just stick to it. Especially that we don't apply many styles ourselves.

2022-09-26 14:17 UTC, jakubfiglak commented
> I see that some types changed, especially from required to not required, for now I did enough to pass build but should I create ticket for overall changes ?

Nah, if the build is passing, everything should be fine. That's what the workflow is for :D

2022-09-26 14:20 UTC, jakubfiglak commented on src/pages/dashboard.tsx
> +    limit: 2,
Oh, it doesn't make any sense, I'll create a ticket for that - will fix FE later

2022-09-26 14:31 UTC, jakubfiglak approved these changes
There's still some comments, I'll leave it up to you if you want to address them or not. Especially this thing with forwarding props on `StyledAvatar` component bugs me. This is a really simple thing and we shouldn't need to do such stuff. Sometimes it's better to repeat yourself (in files you're using `StyledAvatar`) than to add unnecessary layer of complexity.

2022-09-26 14:31 UTC, jakubfiglak commented on src/modules/dashboard/CountCard.tsx
> +})
I'd still use `sx` prop for this, there's really not so many properties. And this is definitely "one-time" styling (it's private to `CountCard` component). But I'll leave it up to you.

2022-09-26 14:31 UTC, jakubfiglak commented on public/locales/en/common.json
>  }
You might wanna take a look why your editor doesn't add `newline` at the end of json files

2022-09-26 14:31 UTC, jakubfiglak commented on src/modules/dashboard/StyledAvatar.tsx
> +  shouldForwardProp: prop => prop !== 'secondary',
Why do we need this crazy thing here? :D

2022-09-27 15:06 UTC, dejwi commented on public/locales/en/common.json
>  }
It adds it when I press CTRL+S by myself, auto save doesnt format + using create-translations doesnt add new line🙆‍♂️🙆‍♂️

2022-09-27 15:07 UTC, dejwi commented on src/modules/dashboard/StyledAvatar.tsx
> +  shouldForwardProp: prop => prop !== 'secondary',
mui things😅

2022-09-27 15:09 UTC, merged