Feat/scout 178 filters hiding
scoutmaker/scoutmaker-web-v2 pull request #48
Opened 2022-09-21 17:02 UTC by dejwi

### Task Description

Dostałem od Jacka sugestię, żeby filtry nie zasłaniały pół ekranu, więc wpakowałem je do accordina i no narazie obczaj sobie bez akceptowania
Dodane na /players

Kwestie czy na każdym formie czy tylko na dłuższych, jak na mobilce itd i czy w ogóle ten format pasuje

2022-09-26 17:39 UTC, dejwi commented
@jakubfiglak na pierwszy rzut oka może wydawać się pogmatwane, w skrócie użyłem nazwy kluczy z obiektu filters, bo prawie zawsze są takie same i we wszystkich combo np jak jest competitionGroupIds to można odrazu wywnioskować docelowy typ obiektu i tym samym wyodrębnić uprganione dane

2022-09-26 19:48 UTC, jakubfiglak requested changes
I don't think we can accomplish want we want regarding displaying applied filters with this approach. What I'd suggest to focus on within this PR is to create UI for hiding filter forms in the accordion. We can tackle displaying applied filters when we're done with this refactor https://github.com/scoutmaker/scoutmaker-web-v2/pull/54. 

For now, I'm not sure if I like dark background on the `AccordionSummary`, please try and use the default one. Also, please use `expandIcon` on this component.

2022-09-26 19:48 UTC, jakubfiglak commented on src/components/filter-accordion/getFiltersText.ts
> +    if (!value) return
This is why you had this eslint error: `/* eslint-disable consistent-return  */` - one branch of your function returns nothing, other ones return `finalArray`

2022-09-26 19:48 UTC, jakubfiglak commented on src/components/filter-accordion/getTextFromKey.tsx
> +  })
How would you make this reusable?

2022-09-26 20:18 UTC, dejwi commented on src/components/filter-accordion/getTextFromKey.tsx
> +  })
problem is IT'S ALREADY REUSABLE - I'll explain more in a second

2022-09-26 20:41 UTC, dejwi commented
I think there's been a misunderstanding because it's already fully REUSABLE.
I've made 2 commits that adds FULL functionality to `/user-subscriptions`.
First commit exits only because for now I made types/keyTextMap applicable fully only to `/players`, so when everything is added second commit is what's needed to reuse my accordion.
PLEASE CHECK🙏🙏

2022-09-26 20:55 UTC, dejwi commented on src/components/filter-accordion/getFiltersText.ts
> +    if (!value) return
`return finalArray` is outside this function and empty returns are just to skip to the next iteration(as basicly all returns there)

I broke the DRY rule here but it's for tomorrow😅

2022-09-26 20:57 UTC, dejwi commented on src/components/filter-accordion/getFiltersText.ts
> +    if (!value) return
I understand that but why value of return matters on `.forEach` 😅

I broke the DRY rule here but it's for tomorrow

2022-09-27 07:34 UTC, jakubfiglak requested changes
Once again - great job trying to figure this out but I don't think this is a right solution to our problem. We have a general issue with how we handle filter data, let's take teams list data as an example. Currently the flow looks like this:

- we fetch data from `/teams/list` endpoint - response is of a type `TeamBasicDataDto[]`,
- we pass this data to `TeamsCombo` component, we extract the id, we keep this as the input value, and do some crazy shit to get a display label:

```
      getOptionLabel={(option: string) => {
        if (option === '') {
          return ''
        }
        const team = data.find(c => c.id === option)
        if (team) {
          return team.name
        }
        return t('NONE')
      }}
```
- our filter state is of a type `string[]`
- now we want to display filters in a user friendly way (user doesn't care about ids, for them it's just a random jibber jabber)
- we need to do crazy shit AGAIN to basically GET BACK from `string[]` to `TeamBasicDataDto[]`

We can avoid doing all this work by simply keeping `TeamBasicDataDto` in our filter state. We could then display it if we want, map to ids and send to backend. This is actually much more flexible - we can also keep more data in state and for example conditionally render some filter inputs (like it's been requested in this ticket - https://playmakerpro.atlassian.net/browse/SCOUT-186). It would not be possible with our current approach. I know it requires big refactor but I think it's worth it. Let me know what you think.

2022-09-27 07:34 UTC, jakubfiglak commented on src/components/filter-accordion/getTextFromKey.tsx
> +  })
Sorry but I cannot agree that this is reusable:) What if we had 200 different filter types in our application? Or a 1000? I mean, you're doing a great job trying to figure this out but I think we should change the approach here, I will explain what architectural issue I see in review summary.

2022-09-28 18:24 UTC, jakubfiglak commented
Please do not abandon the work you've done here. The ticket (https://playmakerpro.atlassian.net/browse/SCOUT-178) is about providing option to hide filters, so let's focus on that - put the form inside the accordion and that's it. We will worry about displaying applied filters later.

2022-09-29 09:13 UTC, dejwi commented
By default you mean this or white? and do we keep `changed` chip for now or delete it
![image](https://user-images.githubusercontent.com/80927085/192991677-9bd96fee-17df-402d-a624-4ab19b962300.png)

2022-09-30 07:00 UTC, jakubfiglak reviewed
I'd get rid of the chip for now. And I'd apply all these changes to every module.

BTW, what if we do another thing - we can make the filter form full screen width for desktop and place inputs side by side? What do you think? I believe Jacek's already suggested such a change. Can you try it?

2022-09-30 12:44 UTC, jakubfiglak commented
> Side by side you mean like 2 columns ?

Maybe even more? I'm not sure what's going to look and feel nice, I encourage you to experiment. You can go to some well known websites and look at their ui implementation, here's Zalando for example:

![Screenshot 2022-09-30 at 14 41 59](https://user-images.githubusercontent.com/55458549/193272519-cea940f5-7513-44ff-a75c-d0c39741efe8.png)

![Screenshot 2022-09-30 at 14 42 33](https://user-images.githubusercontent.com/55458549/193272534-2884d26f-02c0-4892-b044-749b6903bc27.png)

2022-09-30 14:36 UTC, dejwi commented
@jakubfiglak what do you think of this?? `/players` + it's pretty responsive
flex breakpoint in form container is for keeping columns at max '3'  as above that it looks ugly

Maybe we could change this footed-select to combo ? This misaligned text bugs me a lot

note: had to change mui grid to box because of this:
![image](https://user-images.githubusercontent.com/80927085/193291755-e1bf1154-4505-437b-80d6-d72705e3ddac.png)

2022-09-30 14:41 UTC, dejwi commented
I've made the mistake of editing form container directly again I'll separate it but `/players` POC works😅

2022-09-30 17:23 UTC, dejwi commented
Yes I've tried to fix it but currently failed to
What's the problem `flexBasis` ? It scales and basically regulates the number of columns as it's not grid to achieve this cool filled effect
^made some fixes

2022-10-04 16:36 UTC, jakubfiglak reviewed
Looks good to me. I think we can apply this to all filter forms throughout the app. 

One thing though - I think you can try and make this accordion look a little bit nicer. I know I told you to change the background colour to white but it was not a good idea - it should contrast from the background. And I think it'd be good if it had `border-radius` exactly like the table below. Just try and make it look nice please :D

2022-10-04 16:36 UTC, jakubfiglak commented on src/components/filter-accordion/filter-accordion.tsx
> +const StyledAccordinText = styled(Typography)({
There's still a typo :D

2022-10-04 16:36 UTC, jakubfiglak commented on src/components/filter-accordion/filter-accordion.tsx
> +  textAlign: 'center',
I'd left align it personally.

2022-10-07 09:48 UTC, dejwi commented
I think that center text looks better, left align isn't included in new commits
![image](https://user-images.githubusercontent.com/80927085/194525702-9c04b8bd-a0ca-44f2-8e5b-f225cb09680f.png)

2022-10-10 15:57 UTC, jakubfiglak approved these changes

2022-10-11 14:38 UTC, merged