Feat/landing pages
scoutmaker/scoutmaker-web-v2 pull request #49
Opened 2022-09-25 11:44 UTC by dejwi

### Task Description
[SCOUT-157](https://playmakerpro.atlassian.net/browse/SCOUT-157?atlOrigin=eyJpIjoiNWY2NmNkNzMyZGU2NDNlZmJiYWY1NzIzZjY4YmUzZjQiLCJwIjoiaiJ9)
[SCOUT-158](https://playmakerpro.atlassian.net/browse/SCOUT-158?atlOrigin=eyJpIjoiMjc3ZGFlNmMxYzNjNDNmOTkxNjIyYTQ5MjJlYTI2MWEiLCJwIjoiaiJ9)
[SCOUT-159](https://playmakerpro.atlassian.net/browse/SCOUT-159?atlOrigin=eyJpIjoiNjhmZTYxZWExZTc3NGZjNDhiM2M3NmEwNWU0ZTRjOGIiLCJwIjoiaiJ9)
[SCOUT-160](https://playmakerpro.atlassian.net/browse/SCOUT-160?atlOrigin=eyJpIjoiZjQxZTVhY2M0ZmYzNDdhYmJlMjEzMmQ2OWE0ZjRiMDAiLCJwIjoiaiJ9)
[SCOUT-161](https://playmakerpro.atlassian.net/browse/SCOUT-161?atlOrigin=eyJpIjoiZDk3N2ZiYTk5ZGI2NDEzNTgxZDZmMGNjZGQ0NmVlMDUiLCJwIjoiaiJ9)

- home, club-scouting, data-analysis, scouting-academy, scouting-app PAGES/MODULES
- shared landing components

### Additional Notes (optional)
- misses sending emails and getting app numbers as in v1 there were email and dashboard endpoints

2022-09-25 13:47 UTC, jakubfiglak requested changes
I'm sorry but over 4000 lines of a PR is almost impossible to review. I just scanned it and I see a couple of issues:

1) Please use `Image` component from `NextJS` whenever it's possible - https://nextjs.org/docs/api-reference/next/image
2) I think we can use `getStaticProps` instead of `getServerSideProps` for our landing pages - please read about differences in the docs - https://nextjs.org/docs/basic-features/data-fetching/get-static-props
3) You sometimes disable eslint when it's telling you the right thing to do:)
4) You should never use `@ts-ignore`. Whenever you find yourself wanting to do it, it means you've done something really strange with your code. It's a total red flag, please do not do it.
5) There are some errors in the console:

<img width="667" alt="Screenshot 2022-09-25 at 15 46 28" src="https://user-images.githubusercontent.com/55458549/192146877-deb5b703-452d-432e-b699-f54139d0eefe.png">

<img width="993" alt="Screenshot 2022-09-25 at 15 46 36" src="https://user-images.githubusercontent.com/55458549/192146887-2d8fb77e-1893-49fb-906c-3b0ddaf6672f.png">

But generally - great work 🚀

2022-09-25 13:47 UTC, jakubfiglak commented on src/components/forms/container.tsx
> -
Why did you delete these lines? It made forms grow to ridiculous size throughout entire app

![Screenshot 2022-09-25 at 15 26 32](https://user-images.githubusercontent.com/55458549/192146014-c4e85005-97aa-48e3-b6db-41964648b636.png)

2022-09-25 13:47 UTC, jakubfiglak commented on src/components/landing/AdvantageTile.tsx
> +}))
For mui components like `Typography`, you could've used `sx` prop.

2022-09-25 13:47 UTC, jakubfiglak commented on src/components/landing/AdvantagesSection.tsx
> +    <Box component='section' sx={containerStyle}>
What's the benefit on extracting `containerStyle` to a variable?

2022-09-25 13:47 UTC, jakubfiglak commented on src/components/landing/CopySection.tsx
> +          <Box component='img' src={image.src} alt={image.alt} width='100%' />
Why did you do it like this? Please use `Image` component from `next`

2022-09-25 13:47 UTC, jakubfiglak commented on src/components/landing/EffectCard.tsx
> +const Image = styled('img')({
Please use `Image` component from nextjs

2022-09-25 13:47 UTC, jakubfiglak commented on src/components/landing/EffectsSection.tsx
> +      // justifyContent="space-between" CHECK
Please remove comments

2022-09-25 13:47 UTC, jakubfiglak commented on src/modules/landing-academy/data.tsx
> +      {/* eslint-disable-next-line react/jsx-no-useless-fragment */}
Why did you disable eslint here? I don't see a reason to use a fragment here as well :D

2022-09-25 13:47 UTC, jakubfiglak commented on src/modules/landing-app/FunctionalitySection.tsx
> +              // @ts-ignore
Why?

2022-09-25 13:47 UTC, jakubfiglak commented on src/pages/club-scouting.tsx
> +)
Is there a reason we should use `withSessionSsr` here? All these pages should be publicly available and shouldn't care about a session at all I suppose. Another thing is that I think they can be statically generated so perhaps we can consider using `getStaticProps` instead of `getServerSideProps`? It applies to all of the landing pages.

2022-09-27 21:07 UTC, dejwi commented on src/modules/landing-academy/data.tsx
> +      {/* eslint-disable-next-line react/jsx-no-useless-fragment */}
it was there because without it `<p> </p>` threw error about that multiple components inside are not allowed and `<p>` added perfect padding so I went the lazy way😅 
_Refactored by now_

2022-09-27 21:24 UTC, dejwi commented on src/pages/club-scouting.tsx
> +)
no reason, fixed 🙏

2022-09-28 18:25 UTC, jakubfiglak commented on src/components/forms/container.tsx
> -
Alright, good lesson for the future:)

2022-09-28 19:16 UTC, jakubfiglak reviewed
Getting closer, just couple more comments, including the solution to your Typescript problem:)

2022-09-28 19:16 UTC, jakubfiglak commented on src/components/landing/Footer/components.tsx
> +import { Divider as DDivider, styled } from '@mui/material'
It's always better to prefix component name with library name when you need to rename it - in this case I'd suggest `MuiDivider`

2022-09-28 19:16 UTC, jakubfiglak commented on src/components/landing/HeroSection/components.tsx
> +  shouldForwardProp: prop => prop !== 'backgroundImage',
Why do we need to do this?

2022-09-28 19:16 UTC, jakubfiglak commented on src/modules/landing-app/FunctionalitySection.tsx
> +              // @ts-ignore
There's much more elegant solution to this issue - https://mui.com/material-ui/guides/typescript/#complications-with-the-component-prop

Or you could've just used `sx` prop and you wouldn't have this issue at all:)

2022-09-28 19:16 UTC, jakubfiglak commented on src/modules/landing-app/data.tsx
> +      {/* eslint-disable-next-line react/jsx-no-useless-fragment */}
Why are you doing this? Isn't this fragment indeed useless?:)

2022-09-28 19:19 UTC, jakubfiglak commented on src/modules/landing-academy/data.tsx
> +      {/* eslint-disable-next-line react/jsx-no-useless-fragment */}
But I don't believe a fragment is solving this issue. It renders literally nothing so the issue with nested `p` tags will stil  be relevant. You can always use `span`

2022-09-28 21:21 UTC, dejwi commented on src/components/landing/HeroSection/components.tsx
> +  shouldForwardProp: prop => prop !== 'backgroundImage',
if you're talking about `shouldForwardProp`, I found this way when searching about passing props and last time it threw some errors in console without it, tested it now here and it doesnt🥲 I guess it threws them only when its boolean prop

2022-09-28 21:22 UTC, dejwi commented on src/components/landing/AdvantagesSection.tsx
> +    <Box component='section' sx={containerStyle}>
you're right😭

2022-09-29 06:47 UTC, jakubfiglak commented on src/components/landing/HeroSection/components.tsx
> +  shouldForwardProp: prop => prop !== 'backgroundImage',
You mean something like `...doesn't recognize prop blahblahblah on a DOM node` ? That's interesting, I encountered this error too and I didn't know what to do with it :D

2022-09-29 08:45 UTC, dejwi commented on src/components/landing/HeroSection/components.tsx
> +  shouldForwardProp: prop => prop !== 'backgroundImage',
![image](https://user-images.githubusercontent.com/80927085/192984782-2a1398ca-e9f5-407c-afc5-a60db9a264c1.png)
smth like this🙆‍♂️

2022-09-30 06:01 UTC, jakubfiglak approved these changes

2022-09-30 12:29 UTC, merged