Fix/scout 185 blocked filters
scoutmaker/scoutmaker-web-v2 pull request #65
Opened 2022-10-03 14:31 UTC by dejwi

### Task Description
[SCOUT-185](https://playmakerpro.atlassian.net/browse/SCOUT-185?atlOrigin=eyJpIjoiMjEwNzYyMzkxM2UwNGFjYTg0MjBmN2I5NzY5OWYzYTciLCJwIjoiaiJ9)

`isSubmitting` was stuck on `true` after second submit and only combo/checkobx components disabled I still have no idea why 

other solution was to set `disabled="false"` on broken fileds but after implementing that I found new way😭

### Other fixes I included
- fixed nav href from `reporttemplates` to `report-templates`
- fixed level on competition filter as by default it was set to 0 and you couldn't submit

2022-10-04 17:16 UTC, jakubfiglak requested changes
Not the most elegant solution but it works, that's fine. Nice job figuring it out 🚀 

Just some stuff with the additional fixes you made need changes.

2022-10-04 17:16 UTC, jakubfiglak commented on src/components/nav/nav-list.tsx
>          />
Actually, we don't need this element at all, please remove it. We already have a link to `report-templates` inside `ExpandeableNavElement` with the title of `t('TEMPLATES')`

2022-10-04 17:16 UTC, jakubfiglak commented on src/pages/competitions/index.tsx
> +  level: '',
This is not a good way to do it. Please don't ever use `@ts-ignore`. `level=0` should be filtered out before form submission

2022-10-04 17:32 UTC, dejwi commented on src/pages/competitions/index.tsx
> +  level: '',
it's filtered, I guess in validation min is set to 1 but displaying level as 0 in cleared form instead of empty field kinda bugs me, maybe we could add to the filter type that level can be empty string too ??

2022-10-04 17:36 UTC, jakubfiglak commented on src/pages/competitions/index.tsx
> +  level: '',
Yeah, that's probably the best solution. I think we should not use input type `number` in that case.

2022-10-04 17:56 UTC, dejwi commented on src/pages/competitions/index.tsx
> +  level: '',
orrr maybe we can use `type="tel"` on all number fields ? I've just learned that it pulls up numeric keyboard on mobile so I think that's kinda useful;p

2022-10-05 06:09 UTC, jakubfiglak commented on src/pages/competitions/index.tsx
> +  level: '',
Noo, I don't think so. This is definitely not a phone number so using `type="tel"` might be confusing and generally not correct.

2022-10-06 14:36 UTC, dejwi commented
I think we should not change input type as we keep the html validation

2022-10-11 14:44 UTC, merged