feat: expand gotomatch functionality & quick notes
scoutmaker/scoutmaker-web-v2 pull request #81
Opened 2022-10-26 17:27 UTC by dejwi

### Task Description
[SCOUT-230](https://playmakerpro.atlassian.net/browse/SCOUT-230?atlOrigin=eyJpIjoiYzVjYjU5ZDg5M2EyNGM4NmEzZDRhMmRhYjc3YTY1MWQiLCJwIjoiaiJ9)

- leave match button leaves match instead of being a link

quick notes:
- nav btn goes now to /notes/create?useMatchAttendance=true
- fetches match attendance and fills&disables match field
- fetches players with teamIds param from match attendance

2022-10-29 18:04 UTC, jakubfiglak requested changes
Good work, but there's still some work to be done here, please see my comments.

Also, I've encountered an error like so, could you please take a look at this?

![Screenshot 2022-10-29 at 19 53 33](https://user-images.githubusercontent.com/55458549/198846446-2d66866b-dfb6-4c95-9249-2030ea0c74aa.png)

2022-10-29 18:04 UTC, jakubfiglak commented on src/pages/notes/create.tsx
> +  })
We cannot use `usePlayers` hook here since it returns paginated response with the maximum count of 20 documents. What if there are more than 20 players in both teams combined? Not to mention that we're fetching much more data than we actually need. Why did you decide to change the hook here?

2022-10-31 17:12 UTC, dejwi commented on src/pages/notes/create.tsx
> +  })
my mistake, I didn't think to use params with list as I didn't saw that anywhere on swagger docs before

2022-11-01 15:00 UTC, jakubfiglak approved these changes

2022-11-01 19:26 UTC, merged