Feat/scout 186 comp group hiding
scoutmaker/scoutmaker-web-v2 pull request #86
Opened 2022-11-02 21:11 UTC by dejwi

### Task Description
[SCOUT-186](https://playmakerpro.atlassian.net/browse/SCOUT-186?atlOrigin=eyJpIjoiZmFkYTE2M2FkYzlkNDJhNDgzMDIzMDMxY2NmNDgzMDIiLCJwIjoiaiJ9)

- conditional display of competition groups combo data based on competitions
- extracted to reusable component
- POC at `/players`

What do you think about this? I think that client filtering is better as it's instant

2022-11-07 17:21 UTC, jakubfiglak requested changes
I think we're overcomplicating things a bit here, I'd opt out from trying to extract this to a reusable piece, at least in a way you proposed. Please see my comments. Good work though - it's nice that you thought of group filtering based on selected competitions.

2022-11-07 17:21 UTC, jakubfiglak commented on src/modules/players/forms/filter.tsx
> +  const formRef = useRef<FormikProps<PlayersFiltersState>>(null)
Why did you use ref here? You have access to form values in a render prop (line 59)

2022-11-07 17:21 UTC, jakubfiglak commented on src/components/filteredCompetitionGroups/filteredCompetitionGroups.tsx
> +const FilteredCompetitionGroups = ({
I don't like the name of this component, it's not explicit enough for me (I should be able to tell what's its responsibility by the name alone). I have no better name in mind though and I think it'd be really hard to come up with a reasonable one. That makes me think that this component might be doing too much. I think we can try and split it into two smaller reusable pieces, especially since I see some other potential problems.

2022-11-07 17:21 UTC, jakubfiglak commented on src/components/filteredCompetitionGroups/filteredCompetitionGroups.tsx
> +        name={competitionsMultiple ? 'competitionIds' : 'competitionId'}
I don't think we should hardcode the name here if we want it to be really reusable

2022-11-07 17:21 UTC, jakubfiglak commented on src/components/filteredCompetitionGroups/filteredCompetitionGroups.tsx
> +          name={groupsMultiple ? 'competitionGroupIds' : 'competitionGroupId'}
Same here

2022-11-07 17:21 UTC, jakubfiglak commented on src/modules/players/forms/filter.tsx
> -              multiple
Why don't we try and decide wether we want to render this component and with what data at this level? We can conditionally render it based on `values.competitionIds` (btw, this should no longer be named like this since it's not only storing ids) and pass filtered `competitionGroupsData` down to `FilterCombo`, can't we?

2022-11-10 09:55 UTC, dejwi commented on src/modules/players/forms/filter.tsx
> +  const formRef = useRef<FormikProps<PlayersFiltersState>>(null)
my bad, I didn't know that

2022-11-10 09:57 UTC, dejwi commented
What about something like this? I think the name of the component now represents what is does well

2022-11-10 21:26 UTC, jakubfiglak approved these changes
It looks much better now, good job 👍

2022-11-10 21:26 UTC, jakubfiglak commented on src/components/combo/combo.tsx
> +    )
What happened here? 🤨

2022-11-11 12:09 UTC, dejwi commented on src/components/combo/combo.tsx
> +    )
ESLint stuff🤷‍♂️

2022-11-13 00:39 UTC, merged