feat: app mappers
scoutmaker/scoutmaker-web-v2 pull request #89
Opened 2022-11-09 21:41 UTC by dejwi

### Task Description
[SCOUT-228](https://playmakerpro.atlassian.net/browse/SCOUT-228?atlOrigin=eyJpIjoiY2I4MThiZDQ2OGY4NDUwMDllYjljMDA0N2ZjNGMwMGQiLCJwIjoiaiJ9)

- fixed rating filtering on notes&reports

not fun types

2022-11-10 21:36 UTC, jakubfiglak requested changes
Please clean up filter types:)

2022-11-10 21:36 UTC, jakubfiglak commented on src/pages/notes/index.tsx
> +      ) as unknown as NotesFiltersState,
What the hell is this 🤣 Please clean up these types, I'm sure there's a better way to handle this. Please remember that using `as` is a last resort - it basically makes Typescript useless

2022-11-14 08:08 UTC, jakubfiglak requested changes
Pretty close but there's a way to do it without using type casting at all:)

2022-11-14 15:52 UTC, dejwi commented
😅

2022-11-15 07:59 UTC, jakubfiglak approved these changes
🎉

2022-11-15 12:56 UTC, merged