Feat/scout 262 more liked filters
scoutmaker/scoutmaker-web-v2 pull request #91
Opened 2022-11-10 17:07 UTC by dejwi

### Task Description
[SCOUT-262](https://playmakerpro.atlassian.net/browse/SCOUT-262?atlOrigin=eyJpIjoiYjExNmI1NjUwNzljNGMyZDljNDg4ODgzZjU2ZjZjMmIiLCJwIjoiaiJ9)

- added teams list params
- added liked teams& players filters on `notes` `reports`

2022-11-14 08:22 UTC, jakubfiglak requested changes
Good job, just one thing to improve

2022-11-14 08:22 UTC, jakubfiglak commented on src/pages/notes/index.tsx
> +  const [filterLikedPlayers, setLikedPlayers] = useState(false)
Why did you create separate pieces of state for this? I don't see a reason why we couldn't just use `filters.onlyLikedPlayers` and `filters.onlyLikedTeams` directly to achieve the same result. There's a rule in state management that you shouldn't keep in state anything you can derive from some other state values - I think it's perfectly applicable here. In fact, you're not even deriving it, you want it to be exactly the same value, am I right?

2022-11-14 08:22 UTC, jakubfiglak commented on src/pages/reports/index.tsx
> +  const [filterLikedPlayers, setLikedPlayers] = useState(false)
The same as in notes, I believe these `useState` calls are redundant

2022-11-14 15:42 UTC, dejwi commented on src/pages/notes/index.tsx
> +  const [filterLikedPlayers, setLikedPlayers] = useState(false)
yes you're right

2022-11-15 08:00 UTC, jakubfiglak approved these changes

2022-11-16 17:59 UTC, merged