[SCOUT-250] unassigned tab
scoutmaker/scoutmaker-web-v2 pull request #96
Opened 2022-11-21 20:41 UTC by jakubfiglak

### Task Description

- Display unassigned notes table on single match page (http://localhost:3000/matches/{matchId})

https://user-images.githubusercontent.com/55458549/203153535-74b03768-a3ce-4fa0-97d6-c6cab47537d4.mov

And a bunch of refactoring ideas/proposals:

- render tabs by looping through a predefined array of data in order to stay DRY inside of jsx
- use `useTabs` hook to manage tabs
- ⚠️ EXPERIMENT: I felt like this whole page file has become hard to read and was doing a little too much by itself so I decided to move all the data fetching logic to a custom hook (this hook is not meant to be reused anywhere else, I'm extracting it to improve readability). @dejwi please let me know what you think about this.

### Additional Notes (optional)

2022-11-22 22:21 UTC, dejwi requested changes
Nicee smaller code is always better, one small question about type names below and what about mobile sizing?
There's too many tabs and they don't fit there with this new section, maybe we can combine 2 teams sections into one where team name is just some slick select input? idk
<img width="762" alt="image" src="https://user-images.githubusercontent.com/80927085/203389902-4447316a-80d0-40f3-9312-db9e5e9ab86e.png">

2022-11-22 22:21 UTC, dejwi commented on src/pages/matches/[id].tsx
> +                } (${docCount})`}
can't types be `NOTES` and `REPORTS` to do just that?
```suggestion
                label={`${t(type)} (${docCount})`}
```

2022-11-22 22:31 UTC, dejwi commented on src/pages/matches/[id].tsx
> +                } (${docCount})`}
not some important stuff but can't types be `NOTES` and `REPORTS` to do just that

```suggestion
                label={`${t(type)} (${docCount})`}
```

2022-11-23 08:05 UTC, jakubfiglak commented on src/pages/matches/[id].tsx
> +                } (${docCount})`}
Respectfully disagree - image if someone comes to do some changes here later and for some reason decides to change the `type` name on our object - how is that person supposed to know that it's gonna break translations? Or the other way around - what if someone wants to change translation key for the heading? Is that person supposed to change the `type`? Then the condition breaks.

Long story short - in this case `type` and i18n key are similar only by coincidence and they shouldn't be dependent on each other

2022-11-23 10:03 UTC, dejwi commented
> What is the issue on this screenshot? Tabs do scroll horizontally don't they? Like with the red arrow on the below screenshot.
> 
> The only thing that bothers me here is the section I marked with the blue rectangle, I can try and tweak font size and padding there
> 
> ![Screenshot 2022-11-23 at 09 01 02](https://user-images.githubusercontent.com/55458549/203497040-51a9e872-d99f-48e6-9ef7-c811bb19b3a6.png)

I was not able to scroll tabs at least on my pc, if you’ll work on this task before I’ll have free time please double check that

2022-11-23 10:14 UTC, jakubfiglak commented
> > What is the issue on this screenshot? Tabs do scroll horizontally don't they? Like with the red arrow on the below screenshot.
> > The only thing that bothers me here is the section I marked with the blue rectangle, I can try and tweak font size and padding there
> > ![Screenshot 2022-11-23 at 09 01 02](https://user-images.githubusercontent.com/55458549/203497040-51a9e872-d99f-48e6-9ef7-c811bb19b3a6.png)
> 
> I was not able to scroll tabs at least on my pc, if you’ll work on this task before I’ll have free time please double check that (if this is the case maybe a overflow-x: scroll would fix that or whatever it was)

You're right, it doesn't work well on smaller devices. I need to think of solution to this, good catch.

2022-11-23 18:21 UTC, jakubfiglak commented
How about now? Slightly different approach

### DESKTOP

Uploading Screen Recording 2022-11-23 at 19.18.50.mov…

### MOBILE

https://user-images.githubusercontent.com/55458549/203620500-eba9ca08-eef7-43af-ba65-bd97fb048d9c.mov

2022-11-29 16:42 UTC, jakubfiglak commented
@dejwi can I get another review please?

2022-11-30 18:24 UTC, dejwi approved these changes
Works a lot better:)

2022-12-01 08:08 UTC, merged